<?php
/**
 * InlineResponse2007DataList
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量开放接口
 *
 * 根据项目需求完成的接口，非所有接口都有相应的代码
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Oceanengine\Open\Model;

use \ArrayAccess;
use \Oceanengine\Open\ObjectSerializer;

/**
 * InlineResponse2007DataList Class Doc Comment
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InlineResponse2007DataList implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_7_data_list';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'convert_rate' => 'int',
        'stat_datetime' => 'string',
        'campaign_id' => 'Null',
        'click' => 'int',
        'id' => 'Null',
        'avg_show_cost' => 'int',
        'campaign_name' => 'Null',
        'cost' => 'int',
        'show' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'convert_rate' => 'int32',
        'stat_datetime' => null,
        'campaign_id' => null,
        'click' => 'int32',
        'id' => null,
        'avg_show_cost' => 'int32',
        'campaign_name' => null,
        'cost' => 'int32',
        'show' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'convert_rate' => 'convert_rate',
        'stat_datetime' => 'stat_datetime',
        'campaign_id' => 'campaign_id',
        'click' => 'click',
        'id' => 'id',
        'avg_show_cost' => 'avg_show_cost',
        'campaign_name' => 'campaign_name',
        'cost' => 'cost',
        'show' => 'show'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'convert_rate' => 'setConvertRate',
        'stat_datetime' => 'setStatDatetime',
        'campaign_id' => 'setCampaignId',
        'click' => 'setClick',
        'id' => 'setId',
        'avg_show_cost' => 'setAvgShowCost',
        'campaign_name' => 'setCampaignName',
        'cost' => 'setCost',
        'show' => 'setShow'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'convert_rate' => 'getConvertRate',
        'stat_datetime' => 'getStatDatetime',
        'campaign_id' => 'getCampaignId',
        'click' => 'getClick',
        'id' => 'getId',
        'avg_show_cost' => 'getAvgShowCost',
        'campaign_name' => 'getCampaignName',
        'cost' => 'getCost',
        'show' => 'getShow'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['convert_rate'] = isset($data['convert_rate']) ? $data['convert_rate'] : null;
        $this->container['stat_datetime'] = isset($data['stat_datetime']) ? $data['stat_datetime'] : null;
        $this->container['campaign_id'] = isset($data['campaign_id']) ? $data['campaign_id'] : null;
        $this->container['click'] = isset($data['click']) ? $data['click'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['avg_show_cost'] = isset($data['avg_show_cost']) ? $data['avg_show_cost'] : null;
        $this->container['campaign_name'] = isset($data['campaign_name']) ? $data['campaign_name'] : null;
        $this->container['cost'] = isset($data['cost']) ? $data['cost'] : null;
        $this->container['show'] = isset($data['show']) ? $data['show'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['convert_rate'] === null) {
            $invalidProperties[] = "'convert_rate' can't be null";
        }
        if ($this->container['stat_datetime'] === null) {
            $invalidProperties[] = "'stat_datetime' can't be null";
        }
        if ($this->container['campaign_id'] === null) {
            $invalidProperties[] = "'campaign_id' can't be null";
        }
        if ($this->container['click'] === null) {
            $invalidProperties[] = "'click' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['avg_show_cost'] === null) {
            $invalidProperties[] = "'avg_show_cost' can't be null";
        }
        if ($this->container['campaign_name'] === null) {
            $invalidProperties[] = "'campaign_name' can't be null";
        }
        if ($this->container['cost'] === null) {
            $invalidProperties[] = "'cost' can't be null";
        }
        if ($this->container['show'] === null) {
            $invalidProperties[] = "'show' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets convert_rate
     *
     * @return int
     */
    public function getConvertRate()
    {
        return $this->container['convert_rate'];
    }

    /**
     * Sets convert_rate
     *
     * @param int $convert_rate convert_rate
     *
     * @return $this
     */
    public function setConvertRate($convert_rate)
    {
        $this->container['convert_rate'] = $convert_rate;

        return $this;
    }

    /**
     * Gets stat_datetime
     *
     * @return string
     */
    public function getStatDatetime()
    {
        return $this->container['stat_datetime'];
    }

    /**
     * Sets stat_datetime
     *
     * @param string $stat_datetime stat_datetime
     *
     * @return $this
     */
    public function setStatDatetime($stat_datetime)
    {
        $this->container['stat_datetime'] = $stat_datetime;

        return $this;
    }

    /**
     * Gets campaign_id
     *
     * @return Null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param Null $campaign_id campaign_id
     *
     * @return $this
     */
    public function setCampaignId($campaign_id)
    {
        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets click
     *
     * @return int
     */
    public function getClick()
    {
        return $this->container['click'];
    }

    /**
     * Sets click
     *
     * @param int $click click
     *
     * @return $this
     */
    public function setClick($click)
    {
        $this->container['click'] = $click;

        return $this;
    }

    /**
     * Gets id
     *
     * @return Null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param Null $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets avg_show_cost
     *
     * @return int
     */
    public function getAvgShowCost()
    {
        return $this->container['avg_show_cost'];
    }

    /**
     * Sets avg_show_cost
     *
     * @param int $avg_show_cost avg_show_cost
     *
     * @return $this
     */
    public function setAvgShowCost($avg_show_cost)
    {
        $this->container['avg_show_cost'] = $avg_show_cost;

        return $this;
    }

    /**
     * Gets campaign_name
     *
     * @return Null
     */
    public function getCampaignName()
    {
        return $this->container['campaign_name'];
    }

    /**
     * Sets campaign_name
     *
     * @param Null $campaign_name campaign_name
     *
     * @return $this
     */
    public function setCampaignName($campaign_name)
    {
        $this->container['campaign_name'] = $campaign_name;

        return $this;
    }

    /**
     * Gets cost
     *
     * @return int
     */
    public function getCost()
    {
        return $this->container['cost'];
    }

    /**
     * Sets cost
     *
     * @param int $cost cost
     *
     * @return $this
     */
    public function setCost($cost)
    {
        $this->container['cost'] = $cost;

        return $this;
    }

    /**
     * Gets show
     *
     * @return int
     */
    public function getShow()
    {
        return $this->container['show'];
    }

    /**
     * Sets show
     *
     * @param int $show show
     *
     * @return $this
     */
    public function setShow($show)
    {
        $this->container['show'] = $show;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


