<?php
/**
 * InterestActionMetrics
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量开放接口
 *
 * 根据项目需求完成的接口，非所有接口都有相应的代码
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Oceanengine\Open\Model;

use \ArrayAccess;
use \Oceanengine\Open\ObjectSerializer;

/**
 * InterestActionMetrics Class Doc Comment
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InterestActionMetrics implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'interestAction_metrics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'stat_cost' => 'string',
        'show_cnt' => 'string',
        'cpm_platform' => 'string',
        'click_cnt' => 'string',
        'ctr' => 'string',
        'cpc_platform' => 'string',
        'convert_cnt' => 'string',
        'conversion_cost' => 'string',
        'conversion_rate' => 'string',
        'deep_convert_cnt' => 'string',
        'deep_convert_cost' => 'string',
        'deep_convert_rate' => 'string',
        'total_play' => 'string',
        'valid_play' => 'string',
        'valid_play_rate' => 'string',
        'valid_play_cost' => 'string',
        'dy_follow' => 'string',
        'dy_like' => 'string',
        'dy_comment' => 'string',
        'dy_share' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'stat_cost' => null,
        'show_cnt' => null,
        'cpm_platform' => null,
        'click_cnt' => null,
        'ctr' => null,
        'cpc_platform' => null,
        'convert_cnt' => null,
        'conversion_cost' => null,
        'conversion_rate' => null,
        'deep_convert_cnt' => null,
        'deep_convert_cost' => null,
        'deep_convert_rate' => null,
        'total_play' => null,
        'valid_play' => null,
        'valid_play_rate' => null,
        'valid_play_cost' => null,
        'dy_follow' => null,
        'dy_like' => null,
        'dy_comment' => null,
        'dy_share' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'stat_cost' => 'stat_cost',
        'show_cnt' => 'show_cnt',
        'cpm_platform' => 'cpm_platform',
        'click_cnt' => 'click_cnt',
        'ctr' => 'ctr',
        'cpc_platform' => 'cpc_platform',
        'convert_cnt' => 'convert_cnt',
        'conversion_cost' => 'conversion_cost',
        'conversion_rate' => 'conversion_rate',
        'deep_convert_cnt' => 'deep_convert_cnt',
        'deep_convert_cost' => 'deep_convert_cost',
        'deep_convert_rate' => 'deep_convert_rate',
        'total_play' => 'total_play',
        'valid_play' => 'valid_play',
        'valid_play_rate' => 'valid_play_rate',
        'valid_play_cost' => 'valid_play_cost',
        'dy_follow' => 'dy_follow',
        'dy_like' => 'dy_like',
        'dy_comment' => 'dy_comment',
        'dy_share' => 'dy_share'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'stat_cost' => 'setStatCost',
        'show_cnt' => 'setShowCnt',
        'cpm_platform' => 'setCpmPlatform',
        'click_cnt' => 'setClickCnt',
        'ctr' => 'setCtr',
        'cpc_platform' => 'setCpcPlatform',
        'convert_cnt' => 'setConvertCnt',
        'conversion_cost' => 'setConversionCost',
        'conversion_rate' => 'setConversionRate',
        'deep_convert_cnt' => 'setDeepConvertCnt',
        'deep_convert_cost' => 'setDeepConvertCost',
        'deep_convert_rate' => 'setDeepConvertRate',
        'total_play' => 'setTotalPlay',
        'valid_play' => 'setValidPlay',
        'valid_play_rate' => 'setValidPlayRate',
        'valid_play_cost' => 'setValidPlayCost',
        'dy_follow' => 'setDyFollow',
        'dy_like' => 'setDyLike',
        'dy_comment' => 'setDyComment',
        'dy_share' => 'setDyShare'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'stat_cost' => 'getStatCost',
        'show_cnt' => 'getShowCnt',
        'cpm_platform' => 'getCpmPlatform',
        'click_cnt' => 'getClickCnt',
        'ctr' => 'getCtr',
        'cpc_platform' => 'getCpcPlatform',
        'convert_cnt' => 'getConvertCnt',
        'conversion_cost' => 'getConversionCost',
        'conversion_rate' => 'getConversionRate',
        'deep_convert_cnt' => 'getDeepConvertCnt',
        'deep_convert_cost' => 'getDeepConvertCost',
        'deep_convert_rate' => 'getDeepConvertRate',
        'total_play' => 'getTotalPlay',
        'valid_play' => 'getValidPlay',
        'valid_play_rate' => 'getValidPlayRate',
        'valid_play_cost' => 'getValidPlayCost',
        'dy_follow' => 'getDyFollow',
        'dy_like' => 'getDyLike',
        'dy_comment' => 'getDyComment',
        'dy_share' => 'getDyShare'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['stat_cost'] = isset($data['stat_cost']) ? $data['stat_cost'] : null;
        $this->container['show_cnt'] = isset($data['show_cnt']) ? $data['show_cnt'] : null;
        $this->container['cpm_platform'] = isset($data['cpm_platform']) ? $data['cpm_platform'] : null;
        $this->container['click_cnt'] = isset($data['click_cnt']) ? $data['click_cnt'] : null;
        $this->container['ctr'] = isset($data['ctr']) ? $data['ctr'] : null;
        $this->container['cpc_platform'] = isset($data['cpc_platform']) ? $data['cpc_platform'] : null;
        $this->container['convert_cnt'] = isset($data['convert_cnt']) ? $data['convert_cnt'] : null;
        $this->container['conversion_cost'] = isset($data['conversion_cost']) ? $data['conversion_cost'] : null;
        $this->container['conversion_rate'] = isset($data['conversion_rate']) ? $data['conversion_rate'] : null;
        $this->container['deep_convert_cnt'] = isset($data['deep_convert_cnt']) ? $data['deep_convert_cnt'] : null;
        $this->container['deep_convert_cost'] = isset($data['deep_convert_cost']) ? $data['deep_convert_cost'] : null;
        $this->container['deep_convert_rate'] = isset($data['deep_convert_rate']) ? $data['deep_convert_rate'] : null;
        $this->container['total_play'] = isset($data['total_play']) ? $data['total_play'] : null;
        $this->container['valid_play'] = isset($data['valid_play']) ? $data['valid_play'] : null;
        $this->container['valid_play_rate'] = isset($data['valid_play_rate']) ? $data['valid_play_rate'] : null;
        $this->container['valid_play_cost'] = isset($data['valid_play_cost']) ? $data['valid_play_cost'] : null;
        $this->container['dy_follow'] = isset($data['dy_follow']) ? $data['dy_follow'] : null;
        $this->container['dy_like'] = isset($data['dy_like']) ? $data['dy_like'] : null;
        $this->container['dy_comment'] = isset($data['dy_comment']) ? $data['dy_comment'] : null;
        $this->container['dy_share'] = isset($data['dy_share']) ? $data['dy_share'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['stat_cost'] === null) {
            $invalidProperties[] = "'stat_cost' can't be null";
        }
        if ($this->container['show_cnt'] === null) {
            $invalidProperties[] = "'show_cnt' can't be null";
        }
        if ($this->container['cpm_platform'] === null) {
            $invalidProperties[] = "'cpm_platform' can't be null";
        }
        if ($this->container['click_cnt'] === null) {
            $invalidProperties[] = "'click_cnt' can't be null";
        }
        if ($this->container['ctr'] === null) {
            $invalidProperties[] = "'ctr' can't be null";
        }
        if ($this->container['cpc_platform'] === null) {
            $invalidProperties[] = "'cpc_platform' can't be null";
        }
        if ($this->container['convert_cnt'] === null) {
            $invalidProperties[] = "'convert_cnt' can't be null";
        }
        if ($this->container['conversion_cost'] === null) {
            $invalidProperties[] = "'conversion_cost' can't be null";
        }
        if ($this->container['conversion_rate'] === null) {
            $invalidProperties[] = "'conversion_rate' can't be null";
        }
        if ($this->container['deep_convert_cnt'] === null) {
            $invalidProperties[] = "'deep_convert_cnt' can't be null";
        }
        if ($this->container['deep_convert_cost'] === null) {
            $invalidProperties[] = "'deep_convert_cost' can't be null";
        }
        if ($this->container['deep_convert_rate'] === null) {
            $invalidProperties[] = "'deep_convert_rate' can't be null";
        }
        if ($this->container['total_play'] === null) {
            $invalidProperties[] = "'total_play' can't be null";
        }
        if ($this->container['valid_play'] === null) {
            $invalidProperties[] = "'valid_play' can't be null";
        }
        if ($this->container['valid_play_rate'] === null) {
            $invalidProperties[] = "'valid_play_rate' can't be null";
        }
        if ($this->container['valid_play_cost'] === null) {
            $invalidProperties[] = "'valid_play_cost' can't be null";
        }
        if ($this->container['dy_follow'] === null) {
            $invalidProperties[] = "'dy_follow' can't be null";
        }
        if ($this->container['dy_like'] === null) {
            $invalidProperties[] = "'dy_like' can't be null";
        }
        if ($this->container['dy_comment'] === null) {
            $invalidProperties[] = "'dy_comment' can't be null";
        }
        if ($this->container['dy_share'] === null) {
            $invalidProperties[] = "'dy_share' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets stat_cost
     *
     * @return string
     */
    public function getStatCost()
    {
        return $this->container['stat_cost'];
    }

    /**
     * Sets stat_cost
     *
     * @param string $stat_cost 消耗
     *
     * @return $this
     */
    public function setStatCost($stat_cost)
    {
        $this->container['stat_cost'] = $stat_cost;

        return $this;
    }

    /**
     * Gets show_cnt
     *
     * @return string
     */
    public function getShowCnt()
    {
        return $this->container['show_cnt'];
    }

    /**
     * Sets show_cnt
     *
     * @param string $show_cnt 展示数
     *
     * @return $this
     */
    public function setShowCnt($show_cnt)
    {
        $this->container['show_cnt'] = $show_cnt;

        return $this;
    }

    /**
     * Gets cpm_platform
     *
     * @return string
     */
    public function getCpmPlatform()
    {
        return $this->container['cpm_platform'];
    }

    /**
     * Sets cpm_platform
     *
     * @param string $cpm_platform 平均千次展示成本
     *
     * @return $this
     */
    public function setCpmPlatform($cpm_platform)
    {
        $this->container['cpm_platform'] = $cpm_platform;

        return $this;
    }

    /**
     * Gets click_cnt
     *
     * @return string
     */
    public function getClickCnt()
    {
        return $this->container['click_cnt'];
    }

    /**
     * Sets click_cnt
     *
     * @param string $click_cnt 点击数
     *
     * @return $this
     */
    public function setClickCnt($click_cnt)
    {
        $this->container['click_cnt'] = $click_cnt;

        return $this;
    }

    /**
     * Gets ctr
     *
     * @return string
     */
    public function getCtr()
    {
        return $this->container['ctr'];
    }

    /**
     * Sets ctr
     *
     * @param string $ctr 点击率
     *
     * @return $this
     */
    public function setCtr($ctr)
    {
        $this->container['ctr'] = $ctr;

        return $this;
    }

    /**
     * Gets cpc_platform
     *
     * @return string
     */
    public function getCpcPlatform()
    {
        return $this->container['cpc_platform'];
    }

    /**
     * Sets cpc_platform
     *
     * @param string $cpc_platform 平均点击单价
     *
     * @return $this
     */
    public function setCpcPlatform($cpc_platform)
    {
        $this->container['cpc_platform'] = $cpc_platform;

        return $this;
    }

    /**
     * Gets convert_cnt
     *
     * @return string
     */
    public function getConvertCnt()
    {
        return $this->container['convert_cnt'];
    }

    /**
     * Sets convert_cnt
     *
     * @param string $convert_cnt 转化数
     *
     * @return $this
     */
    public function setConvertCnt($convert_cnt)
    {
        $this->container['convert_cnt'] = $convert_cnt;

        return $this;
    }

    /**
     * Gets conversion_cost
     *
     * @return string
     */
    public function getConversionCost()
    {
        return $this->container['conversion_cost'];
    }

    /**
     * Sets conversion_cost
     *
     * @param string $conversion_cost 转化成本
     *
     * @return $this
     */
    public function setConversionCost($conversion_cost)
    {
        $this->container['conversion_cost'] = $conversion_cost;

        return $this;
    }

    /**
     * Gets conversion_rate
     *
     * @return string
     */
    public function getConversionRate()
    {
        return $this->container['conversion_rate'];
    }

    /**
     * Sets conversion_rate
     *
     * @param string $conversion_rate 转化率
     *
     * @return $this
     */
    public function setConversionRate($conversion_rate)
    {
        $this->container['conversion_rate'] = $conversion_rate;

        return $this;
    }

    /**
     * Gets deep_convert_cnt
     *
     * @return string
     */
    public function getDeepConvertCnt()
    {
        return $this->container['deep_convert_cnt'];
    }

    /**
     * Sets deep_convert_cnt
     *
     * @param string $deep_convert_cnt 深度转化数
     *
     * @return $this
     */
    public function setDeepConvertCnt($deep_convert_cnt)
    {
        $this->container['deep_convert_cnt'] = $deep_convert_cnt;

        return $this;
    }

    /**
     * Gets deep_convert_cost
     *
     * @return string
     */
    public function getDeepConvertCost()
    {
        return $this->container['deep_convert_cost'];
    }

    /**
     * Sets deep_convert_cost
     *
     * @param string $deep_convert_cost 深度转化成本
     *
     * @return $this
     */
    public function setDeepConvertCost($deep_convert_cost)
    {
        $this->container['deep_convert_cost'] = $deep_convert_cost;

        return $this;
    }

    /**
     * Gets deep_convert_rate
     *
     * @return string
     */
    public function getDeepConvertRate()
    {
        return $this->container['deep_convert_rate'];
    }

    /**
     * Sets deep_convert_rate
     *
     * @param string $deep_convert_rate 深度转化率
     *
     * @return $this
     */
    public function setDeepConvertRate($deep_convert_rate)
    {
        $this->container['deep_convert_rate'] = $deep_convert_rate;

        return $this;
    }

    /**
     * Gets total_play
     *
     * @return string
     */
    public function getTotalPlay()
    {
        return $this->container['total_play'];
    }

    /**
     * Sets total_play
     *
     * @param string $total_play 播放数
     *
     * @return $this
     */
    public function setTotalPlay($total_play)
    {
        $this->container['total_play'] = $total_play;

        return $this;
    }

    /**
     * Gets valid_play
     *
     * @return string
     */
    public function getValidPlay()
    {
        return $this->container['valid_play'];
    }

    /**
     * Sets valid_play
     *
     * @param string $valid_play 播放数
     *
     * @return $this
     */
    public function setValidPlay($valid_play)
    {
        $this->container['valid_play'] = $valid_play;

        return $this;
    }

    /**
     * Gets valid_play_rate
     *
     * @return string
     */
    public function getValidPlayRate()
    {
        return $this->container['valid_play_rate'];
    }

    /**
     * Sets valid_play_rate
     *
     * @param string $valid_play_rate 播放数
     *
     * @return $this
     */
    public function setValidPlayRate($valid_play_rate)
    {
        $this->container['valid_play_rate'] = $valid_play_rate;

        return $this;
    }

    /**
     * Gets valid_play_cost
     *
     * @return string
     */
    public function getValidPlayCost()
    {
        return $this->container['valid_play_cost'];
    }

    /**
     * Sets valid_play_cost
     *
     * @param string $valid_play_cost 有效播放成本
     *
     * @return $this
     */
    public function setValidPlayCost($valid_play_cost)
    {
        $this->container['valid_play_cost'] = $valid_play_cost;

        return $this;
    }

    /**
     * Gets dy_follow
     *
     * @return string
     */
    public function getDyFollow()
    {
        return $this->container['dy_follow'];
    }

    /**
     * Sets dy_follow
     *
     * @param string $dy_follow 有效播放成本
     *
     * @return $this
     */
    public function setDyFollow($dy_follow)
    {
        $this->container['dy_follow'] = $dy_follow;

        return $this;
    }

    /**
     * Gets dy_like
     *
     * @return string
     */
    public function getDyLike()
    {
        return $this->container['dy_like'];
    }

    /**
     * Sets dy_like
     *
     * @param string $dy_like 有效播放成本
     *
     * @return $this
     */
    public function setDyLike($dy_like)
    {
        $this->container['dy_like'] = $dy_like;

        return $this;
    }

    /**
     * Gets dy_comment
     *
     * @return string
     */
    public function getDyComment()
    {
        return $this->container['dy_comment'];
    }

    /**
     * Sets dy_comment
     *
     * @param string $dy_comment 评论提交数
     *
     * @return $this
     */
    public function setDyComment($dy_comment)
    {
        $this->container['dy_comment'] = $dy_comment;

        return $this;
    }

    /**
     * Gets dy_share
     *
     * @return string
     */
    public function getDyShare()
    {
        return $this->container['dy_share'];
    }

    /**
     * Sets dy_share
     *
     * @param string $dy_share 分享数
     *
     * @return $this
     */
    public function setDyShare($dy_share)
    {
        $this->container['dy_share'] = $dy_share;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


