<?php
/**
 * AdvertiserListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Oceanengine\Open;

/**
 * AdvertiserListTest Class Doc Comment
 *
 * @category    Class
 * @description AdvertiserList
 * @package     Oceanengine\Open
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdvertiserListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdvertiserList"
     */
    public function testAdvertiserList()
    {
    }

    /**
     * Test attribute "advertiser_id"
     */
    public function testPropertyAdvertiserId()
    {
    }

    /**
     * Test attribute "advertiser_name"
     */
    public function testPropertyAdvertiserName()
    {
    }

    /**
     * Test attribute "advertiser_role"
     */
    public function testPropertyAdvertiserRole()
    {
    }

    /**
     * Test attribute "is_valid"
     */
    public function testPropertyIsValid()
    {
    }

    /**
     * Test attribute "account_role"
     */
    public function testPropertyAccountRole()
    {
    }

    /**
     * Test attribute "company_list"
     */
    public function testPropertyCompanyList()
    {
    }
}
