<?php
/**
 * EnterpriseOverviewDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量开放接口
 *
 * 根据项目需求完成的接口，非所有接口都有相应的代码
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Oceanengine\Open;

/**
 * EnterpriseOverviewDataTest Class Doc Comment
 *
 * @category    Class
 * @description EnterpriseOverviewData
 * @package     Oceanengine\Open
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EnterpriseOverviewDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EnterpriseOverviewData"
     */
    public function testEnterpriseOverviewData()
    {
    }

    /**
     * Test attribute "business_page_home_visited"
     */
    public function testPropertyBusinessPageHomeVisited()
    {
    }

    /**
     * Test attribute "business_page_home_visited_ucount"
     */
    public function testPropertyBusinessPageHomeVisitedUcount()
    {
    }

    /**
     * Test attribute "business_page_fans_num_all"
     */
    public function testPropertyBusinessPageFansNumAll()
    {
    }

    /**
     * Test attribute "business_page_new_fans_num"
     */
    public function testPropertyBusinessPageNewFansNum()
    {
    }

    /**
     * Test attribute "business_page_disfollow_ucount"
     */
    public function testPropertyBusinessPageDisfollowUcount()
    {
    }

    /**
     * Test attribute "business_page_comment"
     */
    public function testPropertyBusinessPageComment()
    {
    }

    /**
     * Test attribute "business_page_like"
     */
    public function testPropertyBusinessPageLike()
    {
    }

    /**
     * Test attribute "business_page_share"
     */
    public function testPropertyBusinessPageShare()
    {
    }

    /**
     * Test attribute "business_page_dp_down_click_cnt"
     */
    public function testPropertyBusinessPageDpDownClickCnt()
    {
    }

    /**
     * Test attribute "business_page_favourite_video_cnt"
     */
    public function testPropertyBusinessPageFavouriteVideoCnt()
    {
    }

    /**
     * Test attribute "business_page_fw_video_vv"
     */
    public function testPropertyBusinessPageFwVideoVv()
    {
    }

    /**
     * Test attribute "business_page_play_over"
     */
    public function testPropertyBusinessPagePlayOver()
    {
    }

    /**
     * Test attribute "business_page_total_play"
     */
    public function testPropertyBusinessPageTotalPlay()
    {
    }

    /**
     * Test attribute "business_page_dislike_cnt"
     */
    public function testPropertyBusinessPageDislikeCnt()
    {
    }

    /**
     * Test attribute "business_page_chat_by_share_video_cnt"
     */
    public function testPropertyBusinessPageChatByShareVideoCnt()
    {
    }

    /**
     * Test attribute "business_page_click_cart_count"
     */
    public function testPropertyBusinessPageClickCartCount()
    {
    }

    /**
     * Test attribute "business_page_click_product"
     */
    public function testPropertyBusinessPageClickProduct()
    {
    }

    /**
     * Test attribute "business_page_click_product_go_buy"
     */
    public function testPropertyBusinessPageClickProductGoBuy()
    {
    }

    /**
     * Test attribute "business_page_order_count"
     */
    public function testPropertyBusinessPageOrderCount()
    {
    }

    /**
     * Test attribute "business_page_pay_order_count"
     */
    public function testPropertyBusinessPagePayOrderCount()
    {
    }

    /**
     * Test attribute "business_page_pay_order_gmv"
     */
    public function testPropertyBusinessPagePayOrderGmv()
    {
    }
}
