<?php
/**
 * InlineResponse20023DataListTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量开放接口
 *
 * 根据项目需求完成的接口，非所有接口都有相应的代码
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Oceanengine\Open;

/**
 * InlineResponse20023DataListTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20023DataList
 * @package     Oceanengine\Open
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse20023DataListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20023DataList"
     */
    public function testInlineResponse20023DataList()
    {
    }

    /**
     * Test attribute "advertiser_id"
     */
    public function testPropertyAdvertiserId()
    {
    }

    /**
     * Test attribute "transaction_type"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "grant"
     */
    public function testPropertyGrant()
    {
    }

    /**
     * Test attribute "frozen"
     */
    public function testPropertyFrozen()
    {
    }

    /**
     * Test attribute "cash"
     */
    public function testPropertyCash()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "return_goods"
     */
    public function testPropertyReturnGoods()
    {
    }

    /**
     * Test attribute "transaction_seq"
     */
    public function testPropertyTransactionSeq()
    {
    }

    /**
     * Test attribute "remitter"
     */
    public function testPropertyRemitter()
    {
    }

    /**
     * Test attribute "payee"
     */
    public function testPropertyPayee()
    {
    }
}
