<?php
/**
 * InlineResponse20011DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量开放接口
 *
 * 根据项目需求完成的接口，非所有接口都有相应的代码
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Oceanengine\Open;

/**
 * InlineResponse20011DataTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20011Data
 * @package     Oceanengine\Open
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse20011DataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse20011Data"
     */
    public function testInlineResponse20011Data()
    {
    }

    /**
     * Test attribute "metrics_dict"
     */
    public function testPropertyMetricsDict()
    {
    }

    /**
     * Test attribute "province_name"
     */
    public function testPropertyProvinceName()
    {
    }
}
