<?php
/**
 * InlineObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Oceanengine\Open
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 巨量
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Oceanengine\Open;

/**
 * InlineObjectTest Class Doc Comment
 *
 * @category    Class
 * @description InlineObject
 * @package     Oceanengine\Open
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineObject"
     */
    public function testInlineObject()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "secret"
     */
    public function testPropertySecret()
    {
    }

    /**
     * Test attribute "grant_type"
     */
    public function testPropertyGrantType()
    {
    }

    /**
     * Test attribute "auth_code"
     */
    public function testPropertyAuthCode()
    {
    }
}
